id: EWS_O365_test
version: -1
name: EWS_O365_test
fromversion: 5.0.0
starttaskid: "0"
description: ""
tasks:
  "0":
    id: "0"
    taskid: 30cae266-e0a8-452d-8943-665774422b8c
    type: start
    task:
      id: 30cae266-e0a8-452d-8943-665774422b8c
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 07cb9584-cb17-4dfd-84af-8f996a2078b1
    type: regular
    task:
      id: 07cb9584-cb17-4dfd-84af-8f996a2078b1
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: ebdccb18-6f99-4dd7-8f40-1bdfbeb3dc9a
    type: regular
    task:
      id: ebdccb18-6f99-4dd7-8f40-1bdfbeb3dc9a
      version: -1
      name: ews-get-attachment
      script: '|||ews-get-attachment'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      attachment-ids: {}
      item-id:
        simple: AAMkAGZiODc1MGY3LTBiODEtNDQ3ZC05YzdjLWVkYjhiMjFlMTk1MABGAAAAAAB4Hvam6Pd3Sqro7SBw8T0oBwDj9X3Q04QOTYf/bBd1+UDZAAAAAAEMAADj9X3Q04QOTYf/bBd1+UDZAAAHclB6AAA=
      target-mailbox: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 4b3b36e7-7ebd-464d-8221-9b6a6680d9cf
    type: condition
    task:
      id: 4b3b36e7-7ebd-464d-8221-9b6a6680d9cf
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Items.FileAttachments.attachmentId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Items.FileAttachments.attachmentName
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Items.FileAttachments.attachmentSHA256
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 03882cbc-733b-44d7-874f-486e0dd17a01
    type: regular
    task:
      id: 03882cbc-733b-44d7-874f-486e0dd17a01
      version: -1
      name: ews-get-searchable-mailboxes
      script: '|||ews-get-searchable-mailboxes'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: a40c8944-ff91-4708-8b48-35aba2a87385
    type: condition
    task:
      id: a40c8944-ff91-4708-8b48-35aba2a87385
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Mailboxes.mailbox
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Mailboxes.mailboxId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Mailboxes.displayName
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Mailboxes.isExternal
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 14f4b8b0-e919-42b6-8795-1e1ec300580c
    type: regular
    task:
      id: 14f4b8b0-e919-42b6-8795-1e1ec300580c
      version: -1
      name: ews-search-mailbox
      script: '|||ews-search-mailbox'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      folder-path: {}
      is-public: {}
      limit: {}
      message-id: {}
      query:
        simple: move me
      selected-fields: {}
      target-mailbox: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: e344a635-527f-477b-8cfe-5744c5fb982d
    type: condition
    task:
      id: e344a635-527f-477b-8cfe-5744c5fb982d
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: EWS.Items.itemId
            iscontext: true
          right:
            value:
              simple: AAMkAGZiODc1MGY3LTBiODEtNDQ3ZC05YzdjLWVkYjhiMjFlMTk1MABGAAAAAAB4Hvam6Pd3Sqro7SBw8T0oBwDj9X3Q04QOTYf/bBd1+UDZAAAAAAEMAADj9X3Q04QOTYf/bBd1+UDZAAAHclB4AAA=
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: b49a645f-d85d-4022-8cff-fd20396e71da
    type: regular
    task:
      id: b49a645f-d85d-4022-8cff-fd20396e71da
      version: -1
      name: ews-get-contacts
      script: '|||ews-get-contacts'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: f036ee19-dbb4-4292-83e4-9cffeb2eb214
    type: regular
    task:
      id: f036ee19-dbb4-4292-83e4-9cffeb2eb214
      version: -1
      name: ews-get-out-of-office
      script: '|||ews-get-out-of-office'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      target-mailbox:
        simple: avishai@demistodev.onmicrosoft.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "19":
    id: "19"
    taskid: 72287516-243e-4298-86b3-f3e6e5e0c66c
    type: condition
    task:
      id: 72287516-243e-4298-86b3-f3e6e5e0c66c
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "24"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Account.Email.OutOfOffice.state
            iscontext: true
          right:
            value:
              simple: Disabled
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "24":
    id: "24"
    taskid: d4394b74-7e79-4301-87c7-9da82173d405
    type: regular
    task:
      id: d4394b74-7e79-4301-87c7-9da82173d405
      version: -1
      name: ews-find-folders
      script: '|||ews-find-folders'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "25"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "25":
    id: "25"
    taskid: 321b634d-a27c-48f8-8590-2a656e366ff1
    type: condition
    task:
      id: 321b634d-a27c-48f8-8590-2a656e366ff1
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "26"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Folders.name
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Folders.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Folders.totalCount
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Folders.unreadCount
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Folders.changeKey
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Folders.childrenFolderCount
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "26":
    id: "26"
    taskid: 185de202-eb60-4592-8d38-6ddb3b9196fe
    type: regular
    task:
      id: 185de202-eb60-4592-8d38-6ddb3b9196fe
      version: -1
      name: ews-get-items-from-folder
      script: '|||ews-get-items-from-folder'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "28"
    scriptarguments:
      folder-path:
        simple: AllItems
      get-internal-item: {}
      is-public: {}
      limit:
        simple: "5"
      target-mailbox: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "28":
    id: "28"
    taskid: f78c9505-bfae-4b91-83a5-70902bd0e631
    type: regular
    task:
      id: f78c9505-bfae-4b91-83a5-70902bd0e631
      version: -1
      name: ews-get-items
      script: '|||ews-get-items'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "29"
    scriptarguments:
      item-ids:
        simple: AAMkAGZiODc1MGY3LTBiODEtNDQ3ZC05YzdjLWVkYjhiMjFlMTk1MABGAAAAAAB4Hvam6Pd3Sqro7SBw8T0oBwDj9X3Q04QOTYf/bBd1+UDZAAAAAAEMAADj9X3Q04QOTYf/bBd1+UDZAAAHclB6AAA=
      target-mailbox: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "29":
    id: "29"
    taskid: 3fb4a6fa-ba65-4b2e-8993-8d73ca00c4ca
    type: condition
    task:
      id: 3fb4a6fa-ba65-4b2e-8993-8d73ca00c4ca
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "32"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Items.itemId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Items.datetimeReceived
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Items.datetimeSent
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Items.headers
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Items.sender
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Items.subject
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Items.size
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "32":
    id: "32"
    taskid: 9a6a4013-4250-40fd-8fb0-c77aed7a2ccc
    type: regular
    task:
      id: 9a6a4013-4250-40fd-8fb0-c77aed7a2ccc
      version: -1
      name: ews-get-folder
      script: '|||ews-get-folder'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "33"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "33":
    id: "33"
    taskid: 7f866711-bc25-42be-8224-24f6f0011169
    type: condition
    task:
      id: 7f866711-bc25-42be-8224-24f6f0011169
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "34"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Folders.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Folders.name
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Folders.changeKey
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Folders.totalCount
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Folders.childrenFolderCount
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: EWS.Folders.unreadCount
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2995
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "34":
    id: "34"
    taskid: d870470e-2594-40d0-8754-4166df334e34
    type: regular
    task:
      id: d870470e-2594-40d0-8754-4166df334e34
      version: -1
      name: ews-expand-group
      script: '|||ews-expand-group'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "39"
    scriptarguments:
      email-address:
        simple: testgroup-1@demistodev.onmicrosoft.com
      recursive-expansion: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "39":
    id: "39"
    taskid: 07a4fa9e-4548-4ec1-8c33-2833c6282c4f
    type: title
    task:
      id: 07a4fa9e-4548-4ec1-8c33-2833c6282c4f
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3345
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3360,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
