id: CyberTotal_TestPlaybook
version: 20
name: CyberTotal_TestPlaybook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 792dbdae-20a5-4e24-8d70-a2eacd3939c2
    type: start
    task:
      id: 792dbdae-20a5-4e24-8d70-a2eacd3939c2
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 29bbfd5e-e35c-4e4f-8645-6ddbfb85bab0
    type: regular
    task:
      id: 29bbfd5e-e35c-4e4f-8645-6ddbfb85bab0
      version: -1
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all: {}
      index: {}
      key:
        complex:
          root: CyberTotal
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 67198cbe-507b-4ee1-8859-829f8b4f9429
    type: regular
    task:
      id: 67198cbe-507b-4ee1-8859-829f8b4f9429
      version: -1
      name: ip
      description: Return IP information and reputation
      script: CyberTotal|||ip
      type: regular
      iscommand: true
      brand: CyberTotal
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      ip:
        complex:
          root: IP
          accessor: Address
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 79b34dac-eedd-4e3c-89da-86d7b75372bf
    type: condition
    task:
      id: 79b34dac-eedd-4e3c-89da-86d7b75372bf
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.IP.scan_date
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.IP.resource
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.IP.task_id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.IP.permalink
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.IP.severity
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.IP.confidence
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.IP.threat
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.IP.detection_engines
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.IP.positive_detections
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.IP.detection_ratio
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.IP.message
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 87297b8d-ae5d-4c5e-8822-dade1823ed9f
    type: regular
    task:
      id: 87297b8d-ae5d-4c5e-8822-dade1823ed9f
      version: -1
      name: file
      description: Return file's information and reputation
      script: CyberTotal|||file
      type: regular
      iscommand: true
      brand: CyberTotal
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      file:
        complex:
          root: File
          accessor: MD5
      hash:
        complex:
          root: File
          accessor: MD5
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 800
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 4c8b4daa-09eb-4dc1-8b79-26147d6af04d
    type: condition
    task:
      id: 4c8b4daa-09eb-4dc1-8b79-26147d6af04d
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.File.scan_date
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.File.resource
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.File.task_id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.File.permalink
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.File.severity
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.File.confidence
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.File.threat
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.File.detection_engines
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.File.positive_detections
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.File.detection_ratio
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.File.message
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: cb8cf98a-0f95-466c-84dc-a445639f97f7
    type: regular
    task:
      id: cb8cf98a-0f95-466c-84dc-a445639f97f7
      version: -1
      name: domain
      description: Return domain  information and reputation
      script: CyberTotal|||domain
      type: regular
      iscommand: true
      brand: CyberTotal
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      domain:
        complex:
          root: Domain
          accessor: Name
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: cb1eac60-cf39-44ad-81e3-1d5bd48dba3f
    type: condition
    task:
      id: cb1eac60-cf39-44ad-81e3-1d5bd48dba3f
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.Domain.scan_date
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.Domain.resource
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.Domain.permalink
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.Domain.severity
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.Domain.confidence
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.Domain.threat
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.Domain.detection_engines
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.Domain.positive_detections
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.Domain.detection_ratio
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.Domain.message
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 9c051b10-cd2b-4023-82ca-79aa437f913a
    type: regular
    task:
      id: 9c051b10-cd2b-4023-82ca-79aa437f913a
      version: -1
      name: url
      description: Return domain information and reputation
      script: CyberTotal|||url
      type: regular
      iscommand: true
      brand: CyberTotal
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      threshold: {}
      url:
        complex:
          root: URL
          accessor: Data
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 874a3013-ca04-4af0-871b-fc6feb5a6b15
    type: condition
    task:
      id: 874a3013-ca04-4af0-871b-fc6feb5a6b15
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.URL.scan_date
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.URL.resource
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.URL.task_id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.URL.permalink
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.URL.severity
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.URL.confidence
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.URL.threat
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.URL.detection_engines
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.URL.positive_detections
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.URL.detection_ratio
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.URL.message
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1800
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: f489bae9-c130-4faf-8c7e-b36e11ed7283
    type: regular
    task:
      id: f489bae9-c130-4faf-8c7e-b36e11ed7283
      version: -1
      name: cybertotal-ip-whois
      description: Return ip whois information
      script: CyberTotal|||cybertotal-ip-whois
      type: regular
      iscommand: true
      brand: CyberTotal
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      ip:
        complex:
          root: IP
          accessor: Address
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: d7854db1-33d7-42dc-8713-d4139203f5b7
    type: condition
    task:
      id: d7854db1-33d7-42dc-8713-d4139203f5b7
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-IP.scan_date
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-IP.task_id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-IP.resource
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-IP.message
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-IP.permalink
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: be9c2d80-834b-4e8d-8524-e3829e7ad75a
    type: regular
    task:
      id: be9c2d80-834b-4e8d-8524-e3829e7ad75a
      version: -1
      name: cybertotal-url-whois
      description: Return url whois information
      script: CyberTotal|||cybertotal-url-whois
      type: regular
      iscommand: true
      brand: CyberTotal
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      url:
        complex:
          root: URL
          accessor: Data
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: f3f13754-fb03-4b9f-8c7e-bfa9a3d6b323
    type: condition
    task:
      id: f3f13754-fb03-4b9f-8c7e-bfa9a3d6b323
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-URL.scan_date
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-URL.task_id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-URL.resource
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-URL.message
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-URL.permalink
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: b0a72e44-8dd0-4b59-85c0-07788c530209
    type: regular
    task:
      id: b0a72e44-8dd0-4b59-85c0-07788c530209
      version: -1
      name: cybertotal-domain-whois
      description: Return domain whois information
      script: '|||cybertotal-domain-whois'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      domain:
        complex:
          root: Domain
          accessor: Name
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2800
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: bb0919f6-cb69-4494-8898-6b71153b3e73
    type: condition
    task:
      id: bb0919f6-cb69-4494-8898-6b71153b3e73
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-Domain.scan_date
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-Domain.task_id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-Domain.resource
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-Domain.message
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: CyberTotal.WHOIS-Domain.permalink
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: e3fb5c63-d016-49ac-8f20-60aca051c5ba
    type: title
    task:
      id: e3fb5c63-d016-49ac-8f20-60aca051c5ba
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3215,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
