id: fce4731f-9e5e-43e5-85eb-0584cc447686
version: 64
name: CyberTotal Auto Enrichment - CyCraft
description: 'This playbook automatically enriches indicators (including IPs, URLs,
  domains; MD5, SHA-1, and SHA-256 file hashes). Playbook input: the indicators you
  want to enrich.  Playbook output: detection engine results, positive detections,
  detection ratios; as well as severity, confidence, and threat scores.'
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 7404a02f-b757-4717-8a57-a20b7ea21091
    type: start
    task:
      id: 7404a02f-b757-4717-8a57-a20b7ea21091
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 560,
          "y": -30
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 4be584ff-7bfd-4d75-8d10-88a8c5efa673
    type: condition
    task:
      id: 4be584ff-7bfd-4d75-8d10-88a8c5efa673
      version: -1
      name: Is CyberTotal enabled?
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "2"
      - "7"
      - "9"
      - "11"
      - "14"
      - "17"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: CyberTotal
                accessor: brand
            iscontext: true
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 560,
          "y": 140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 0622ee13-b69e-4fa9-8d81-4d79c3e2efb2
    type: condition
    task:
      id: 0622ee13-b69e-4fa9-8d81-4d79c3e2efb2
      version: -1
      name: Is there any URL?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "3"
    scriptarguments:
      value:
        simple: ${inputs.URL}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1750,
          "y": 330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 9b76065f-fbe7-47ad-8ba1-20b88d79037b
    type: regular
    task:
      id: 9b76065f-fbe7-47ad-8ba1-20b88d79037b
      version: -1
      name: Run URL Enrichment
      description: Return domain information and reputation
      script: CyberTotal|||url
      type: regular
      iscommand: true
      brand: CyberTotal
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      long: {}
      retries: {}
      sampleSize: {}
      submitWait: {}
      threshold: {}
      url:
        simple: ${inputs.URL}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1750,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: aac1e3f0-9533-4b6f-843c-75bd6233a148
    type: condition
    task:
      id: aac1e3f0-9533-4b6f-843c-75bd6233a148
      version: -1
      name: Is there any IP?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "8"
    scriptarguments:
      value:
        simple: ${inputs.IP}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1290,
          "y": 330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 3df71e1f-c3d6-4879-8bc8-281020bdaab3
    type: regular
    task:
      id: 3df71e1f-c3d6-4879-8bc8-281020bdaab3
      version: -1
      name: Run IP Enrichment
      description: Return IP information and reputation
      script: CyberTotal|||ip
      type: regular
      iscommand: true
      brand: CyberTotal
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      fullResponse: {}
      ip:
        simple: ${inputs.IP}
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1290,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 849a318a-68f7-40d9-8438-2a6fd13b7f1a
    type: condition
    task:
      id: 849a318a-68f7-40d9-8438-2a6fd13b7f1a
      version: -1
      name: Is there any Domain?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "10"
    scriptarguments:
      value:
        simple: ${inputs.Domain}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 820,
          "y": 330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: e8d1d20d-de15-45de-8405-915cceba61be
    type: regular
    task:
      id: e8d1d20d-de15-45de-8405-915cceba61be
      version: -1
      name: Run Domain Enrichment
      description: Return domain  information and reputation
      script: CyberTotal|||domain
      type: regular
      iscommand: true
      brand: CyberTotal
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      domain:
        simple: ${inputs.Domain}
      fullResponse: {}
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    defaultassigneecomplex: {}
    view: |-
      {
        "position": {
          "x": 820,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 3ded3e2f-22d3-4bd8-8a3f-ed8b91b1400f
    type: condition
    task:
      id: 3ded3e2f-22d3-4bd8-8a3f-ed8b91b1400f
      version: -1
      name: Is there any MD5?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "12"
    scriptarguments:
      value:
        simple: ${inputs.MD5}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 300,
          "y": 330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 30c7040d-ec78-4252-847b-1bafbe1e5fbf
    type: regular
    task:
      id: 30c7040d-ec78-4252-847b-1bafbe1e5fbf
      version: -1
      name: Run MD5 Enrichment
      description: Return file's information and reputation
      script: CyberTotal|||file
      type: regular
      iscommand: true
      brand: CyberTotal
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      file:
        simple: ${inputs.MD5}
      hash:
        simple: ${inputs.MD5}
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 300,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 81eacb62-97e7-476d-86af-0386db955aae
    type: title
    task:
      id: 81eacb62-97e7-476d-86af-0386db955aae
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 560,
          "y": 850
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 39df88b3-efb7-4532-88ba-09ed1440a2f6
    type: condition
    task:
      id: 39df88b3-efb7-4532-88ba-09ed1440a2f6
      version: -1
      name: Is there any SHA1?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "15"
    scriptarguments:
      value:
        simple: ${inputs.SHA1}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -160,
          "y": 330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 9f372c7a-d595-4f93-815d-e21a6ba66b85
    type: regular
    task:
      id: 9f372c7a-d595-4f93-815d-e21a6ba66b85
      version: -1
      name: Run SHA1 Enrichment
      description: Return file's information and reputation
      script: CyberTotal|||file
      type: regular
      iscommand: true
      brand: CyberTotal
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      file:
        simple: ${inputs.SHA1}
      hash:
        simple: ${inputs.SHA1}
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -160,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: aa3465e3-86d5-4a0f-84c5-90bd43319d08
    type: condition
    task:
      id: aa3465e3-86d5-4a0f-84c5-90bd43319d08
      version: -1
      name: Is there any SHA256?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "18"
    scriptarguments:
      value:
        simple: ${inputs.SHA256}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -620,
          "y": 330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: 5347324a-8c8f-44ca-8259-e26a09fdd3f9
    type: regular
    task:
      id: 5347324a-8c8f-44ca-8259-e26a09fdd3f9
      version: -1
      name: Run SHA256 Enrichment
      description: Return file's information and reputation
      script: CyberTotal|||file
      type: regular
      iscommand: true
      brand: CyberTotal
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      file:
        simple: ${inputs.SHA256}
      hash:
        simple: ${inputs.SHA256}
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -620,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {
      "11_12_yes": 0.41,
      "11_13_#default#": 0.14,
      "14_13_#default#": 0.9,
      "1_13_#default#": 0.34,
      "1_2_yes": 0.9,
      "2_13_#default#": 0.14,
      "2_3_yes": 0.41,
      "7_13_#default#": 0.28,
      "7_8_yes": 0.4,
      "9_10_yes": 0.4,
      "9_13_#default#": 0.28
    },
    "paper": {
      "dimensions": {
        "height": 945,
        "width": 2750,
        "x": -620,
        "y": -30
      }
    }
  }
inputs:
- key: Domain
  value:
    complex:
      root: Domain
      accessor: Name
  required: false
  description: The input domain will be searched automatically on CyberTotal to retrieve
    reputation data.
  playbookInputQuery: null
- key: IP
  value:
    complex:
      root: IP
      accessor: Address
  required: false
  description: The input IP will be searched automatically on CyberTotal and to retrieve
    reputation data.
  playbookInputQuery: null
- key: URL
  value:
    complex:
      root: URL
      accessor: Data
  required: false
  description: The input URL will be searched automatically on CyberTotal to retrieve
    reputation data.
  playbookInputQuery: null
- key: MD5
  value:
    complex:
      root: File
      accessor: MD5
  required: false
  description: The input MD5 will be searched automatically on CyberTotal to retrieve
    reputation data.
  playbookInputQuery: null
- key: SHA1
  value:
    complex:
      root: File
      accessor: SHA1
  required: false
  description: The input SHA1 will be searched automatically on CyberTotal to retrieve
    reputation data.
  playbookInputQuery: null
- key: SHA256
  value:
    complex:
      root: File
      accessor: SHA256
  required: false
  description: The input SHA256 will be searched automatically on CyberTotal to retrieve
    reputation data.
  playbookInputQuery: null
outputs: []
sourceplaybookid: 1c314256-6db3-43a7-8aa7-113451a87105
quiet: true
